Add recommendations
VillRom/java-filmorate pull request #12
Opened 2022-10-08 15:44 UTC by Lnepostbox

2022-10-08 17:04 UTC, VillRom requested changes

2022-10-08 17:04 UTC, VillRom commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
>                  + " AND l.id NOT IN (SELECT id FROM likes WHERE user_id = ?) LIMIT ?";
Думаю нам LIMIT не нужен тут

2022-10-08 23:21 UTC, GSBoldyrev approved these changes

2022-10-09 10:29 UTC, VillRom approved these changes
Супер!))

2022-10-09 10:30 UTC, merged